# Used by `staging` branch, per JEKYLL_CONFIG_FILE in Vercel build script
# Unfotunately cannot do deep merging, so we need to rewrite all contentful.spaces keys,
# with addition of api_url: 'preview.contentful.com'

contentful:
  spaces:
    - index:
        space: ENV_CONTENTFUL_SPACE_ID
        access_token: ENV_CONTENTFUL_ACCESS_TOKEN
        base_path: ./source
        destination: /contentful
        all_entries: true
        cda_query:
          content_type: index
        client_options:
          api_url: 'preview.contentful.com'
          max_include_resolution_depth: 2
          reuse_entries: false
    - genericPage:
        space: ENV_CONTENTFUL_SPACE_ID
        access_token: ENV_CONTENTFUL_ACCESS_TOKEN
        base_path: ./source
        destination: /contentful
        all_entries: true
        cda_query:
          content_type: genericPage
        client_options:
          api_url: 'preview.contentful.com'
          max_include_resolution_depth: 2
          reuse_entries: false
    - product:
        space: ENV_CONTENTFUL_SPACE_ID
        access_token: ENV_CONTENTFUL_ACCESS_TOKEN
        base_path: ./source
        destination: /contentful
        all_entries: true
        cda_query:
          content_type: product
        client_options:
          api_url: 'preview.contentful.com'
          max_include_resolution_depth: 2
          reuse_entries: false
    - people:
        space: ENV_CONTENTFUL_SPACE_ID
        access_token: ENV_CONTENTFUL_ACCESS_TOKEN
        base_path: ./source
        destination: /contentful
        all_entries: true
        cda_query:
          content_type: people
        client_options:
          api_url: 'preview.contentful.com'
          max_include_resolution_depth: 2
          reuse_entries: false
    - eventsPage:
        space: ENV_CONTENTFUL_SPACE_ID
        access_token: ENV_CONTENTFUL_ACCESS_TOKEN
        base_path: ./source
        destination: /contentful
        all_entries: true
        cda_query:
          content_type: eventsPage
        client_options:
          api_url: 'preview.contentful.com'
          max_include_resolution_depth: 2
          reuse_entries: false
    - event:
        space: ENV_CONTENTFUL_SPACE_ID
        access_token: ENV_CONTENTFUL_ACCESS_TOKEN
        base_path: ./source
        destination: /contentful
        all_entries: true
        cda_query:
          content_type: event
        client_options:
          api_url: 'preview.contentful.com'
          max_include_resolution_depth: 2
          reuse_entries: false
    - news:
        space: ENV_CONTENTFUL_SPACE_ID
        access_token: ENV_CONTENTFUL_ACCESS_TOKEN
        base_path: ./source
        destination: /contentful
        all_entries: true
        cda_query:
          content_type: news
        client_options:
          api_url: 'preview.contentful.com'
          max_include_resolution_depth: 2
          reuse_entries: false
    - figure:
        space: ENV_CONTENTFUL_SPACE_ID
        access_token: ENV_CONTENTFUL_ACCESS_TOKEN
        base_path: ./source
        destination: /contentful
        all_entries: true
        cda_query:
          content_type: figure
        client_options:
          api_url: 'preview.contentful.com'
          max_include_resolution_depth: 2
          reuse_entries: false
    - initiative:
        space: ENV_CONTENTFUL_SPACE_ID
        access_token: ENV_CONTENTFUL_ACCESS_TOKEN
        base_path: ./source
        destination: /contentful
        all_entries: true
        cda_query:
          content_type: initiative
        client_options:
          api_url: 'preview.contentful.com'
          max_include_resolution_depth: 2
          reuse_entries: false