# Used by `staging` branch, per JEKYLL_CONFIG_FILE in Vercel build script

title: TEST Futures

contentful:
  spaces:
    - index:
        client_options:
          api_url: 'preview.contentful.com'
    - genericPage:
        client_options:
          api_url: 'preview.contentful.com'
    - product:
        client_options:
          api_url: 'preview.contentful.com'
    - people:
        client_options:
          api_url: 'preview.contentful.com'
    - eventsPage:
        client_options:
          api_url: 'preview.contentful.com'
    - event:
        client_options:
          api_url: 'preview.contentful.com'
    - news:
        client_options:
          api_url: 'preview.contentful.com'
    - figure:
        client_options:
          api_url: 'preview.contentful.com'
    - initiative:
        client_options:
          api_url: 'preview.contentful.com'
